"""Asignacion nueva table pagado

Revision ID: 0eef6b212857
Revises: 
Create Date: 2023-03-16 12:41:54.782198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eef6b212857'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado', sa.Boolean(), nullable=True))
        batch_op.drop_column('precio')

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('telefonocasa',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('foto',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('trabajoprecios', schema=None) as batch_op:
        batch_op.alter_column('trabajo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajoprecios', schema=None) as batch_op:
        batch_op.alter_column('trabajo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('telefonocasa',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.INTEGER(), nullable=True))
        batch_op.drop_column('pagado')

    # ### end Alembic commands ###
