"""PiezaPrecio is not unique=true

Revision ID: 2bde2753d038
Revises: 2e86a51be186
Create Date: 2023-01-13 19:21:57.485810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bde2753d038'
down_revision = '2e86a51be186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieza_precios')
    with op.batch_alter_table('pieza_precios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pieza_precio', sa.Float(), nullable=False))
        batch_op.drop_column('precio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieza_precios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.FLOAT(), nullable=False))
        batch_op.drop_column('pieza_precio')

    op.create_table('_alembic_tmp_pieza_precios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_piezas', sa.INTEGER(), nullable=False),
    sa.Column('pieza_precio', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id_piezas'], ['piezas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
