"""pieza_precio_id

Revision ID: 2e86a51be186
Revises: 3b5809e90ac8
Create Date: 2023-01-13 17:23:43.791802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e86a51be186'
down_revision = '3b5809e90ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serviciopiezas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pieza_precio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('pieza_precio_id', 'pieza_precios', ['pieza_precio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serviciopiezas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pieza_precio_id')

    # ### end Alembic commands ###
