"""Initial database

Revision ID: 3b5809e90ac8
Revises: 
Create Date: 2023-01-11 17:21:33.042807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5809e90ac8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historialventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historialventas', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
