"""Empleado todos ya no son unico

Revision ID: 491a74dc907f
Revises: 0eef6b212857
Create Date: 2023-03-26 15:12:35.785495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491a74dc907f'
down_revision = '0eef6b212857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
